# Generated by Django 2.1.3 on 2018-11-22 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist_title',
            new_name='album_title',
        ),
    ]
