# Generated by Django 2.1.3 on 2018-12-04 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='geners',
            new_name='genres',
        ),
    ]
